### PR TITLE
Feature/643 fix 'Model' > 'Simulate Network' also instantiates the model

### LINKED ISSUE #643: 'Model' > 'Simulate Network' also instantiates the model
Steps to recreate:

1. Load tutorial 3b
2. Create Network using 'Model > Create Network' at the top bar
3. Simulate Network using 'Model > Simulate Network' at the top bar

The loading text is not correct, saying 'Instantiating and Simulating the model' leading to the following error

https://user-images.githubusercontent.com/99416933/210222436-8078fd0d-1e7f-4f8a-9327-8c4f356506ef.mov

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/work/NetPyNE-UI/netpyne_ui/netpyne_geppetto.py in simulateNetPyNEModelInGeppetto(self, args)
    312             else:
--> 313                 return self.simulate_single_model(use_prev_inst=use_prev_inst)
    314 

~/work/NetPyNE-UI/netpyne_ui/netpyne_geppetto.py in simulate_single_model(self, experiment, use_prev_inst)
    260                 logging.debug('Instantiating single thread simulation')
--> 261                 netpyne_model = self.instantiateNetPyNEModel()
    262 

~/work/NetPyNE-UI/netpyne_ui/netpyne_geppetto.py in instantiateNetPyNEModel(self)
    668             #simcoded = jsonpickle.encode(self.simConfig, unpicklable=False)
--> 669             sim.create(self.netParams, self.simConfig)
    670             sim.net.defineCellShapes()  # creates 3d pt for cells with stylized geometries

~/work/NetPyNE-UI/src/netpyne/netpyne/sim/wrappers.py in create(netParams, simConfig, output, clearAll)
     57     stims = sim.net.addStims()                    # add external stimulation to cells (IClamps etc)
---> 58     rxd = sim.net.addRxD()                    # add reaction-diffusion (RxD)
     59     simData = sim.setupRecording()             # setup variables to record for each cell (spikes, V traces, etc)

~/work/NetPyNE-UI/src/netpyne/netpyne/network/netrxd.py in addRxD(self, nthreads)
     81         if 'species' in rxdParams:
---> 82             self._addSpecies(rxdParams['species'])
     83         if 'states' in rxdParams:

~/work/NetPyNE-UI/src/netpyne/netpyne/network/netrxd.py in _addSpecies(self, params)
    284                                                             name=name,
--> 285                                                             ecs_boundary_conditions=param['ecs_boundary_conditions'])
    286         else: self.rxd['species'][label]['hObj'] = None

/opt/conda/lib/python3.7/site-packages/neuron/rxd/species.py in __init__(self, regions, d, name, charge, initial, atolscale, ecs_boundary_conditions, represents)
   1634                 self._do_init()
-> 1635                 rxd._update_node_data(True, True)
   1636 

/opt/conda/lib/python3.7/site-packages/neuron/rxd/rxd.py in _update_node_data(force, newspecies)
    639                 _include_flux(True)
--> 640                 _setup_units(force=True)
    641 

/opt/conda/lib/python3.7/site-packages/neuron/rxd/rxd.py in _setup_units(force)
    598             _setup_memb_currents()
--> 599             _compile_reactions()
    600             if _cvode_object.active():

/opt/conda/lib/python3.7/site-packages/neuron/rxd/rxd.py in _compile_reactions()
   1142     for sets in matched_regions:
-> 1143         c_region_list.append(_c_region(sets))
   1144 

/opt/conda/lib/python3.7/site-packages/neuron/rxd/region.py in __init__(self, regions)
     56         self._regions = [weakref.ref(r) for r in regions]
---> 57         self._overlap = self._regions[0]()._secs1d
     58         self.num_regions = len(self._regions)

IndexError: list index out of range

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-129-46909328cfe2> in <module>
----> 1 utils.convertToJS(netpyne_geppetto.simulateNetPyNEModelInGeppetto(utils.convertToPython('{"allTrials":false}')))

~/work/NetPyNE-UI/netpyne_ui/netpyne_geppetto.py in simulateNetPyNEModelInGeppetto(self, args)
    316             message = ("Error while simulating the NetPyNE model: %s. SimulationId %f" % (e, sim_id))
    317             logging.exception(message)
--> 318             return utils.getJSONError(message, sys.exc_info(), { "sim_id": sim_id})
    319 
    320     def _prepare_simulation_files(self, experiment: model.Experiment = None, use_prev_inst: bool = False) -> str:

TypeError: getJSONError() takes 2 positional arguments but 3 were given
```

It might be related to it being instantiated twice, since using the button picker in the upper right, for 'Create Network' and then 'Simulate network' works properly and does not lead to an error.

https://user-images.githubusercontent.com/99416933/210222821-170b792b-1678-4e79-8198-ef7f31ec606f.mov

### PR DESCRIPTION
**Pull request by aranega**
Fixes #643

### CODE REVIEW

**Comment by SimaoBolota-MetaCell** [comment]
It works correctly now 
By following these steps (and similar):

- Load tutorial 3b
- Create Network using 'Model > Create Network' at the top bar
- Simulate Network using 'Model > Simulate Network' at the top bar

an error is no longer displayed and the model is correctly simulated.


https://user-images.githubusercontent.com/99416933/212115309-eb366193-0bf0-4773-95b7-402b9c4b41f8.mov

Additionally, the loader text now has the expected **'Simulating the model'**

'Instantiating and Simulating' works properly as well


https://user-images.githubusercontent.com/99416933/212116792-46071553-10f0-464a-92b2-820fcabf50a6.mov

File: webapp/components/topbar/menuConfiguration.js [hunk 1]
```diff
@@ -328,7 +329,8 @@ export const getModelMenu = (props) => (
           ? [openLaunchDialog()]
           // TODO: (#263) this logic causes issues by potentially simulating
           //  old instance with modified netParams and simConfig
-          : [props.modelState ? createAndSimulateNetwork : simulateNetwork],
+          // : [props.modelState ? createAndSimulateNetwork : simulateNetwork],
+          : [props.modelState === MODEL_STATE.NOT_INSTANTIATED ? createAndSimulateNetwork : simulateNetwork()],
```
Comment (ddelpiano) [inline webapp/components/topbar/menuConfiguration.js:333]: does createAndSimulateNetwork needs () as well? @aranega 

Thanks!

**Review by ddelpiano — APPROVED** [review]
